### ISSUE TITLE
SendTimestamps Could not be constructed

### ISSUE THREAD

**Issue by Serega007RU** [Taimoor-Tariq/BetterDiscordStuff#2]
![image](https://user-images.githubusercontent.com/64780091/147889511-c470a657-532b-477f-b39f-3f66eb87a839.png)
```
SendTimestamps: Could not be constructed.
at PluginManager.initializeAddon (webpack-internal:///./src/modules/pluginmanager.js:159:14)
at PluginManager.loadAddon (webpack-internal:///./src/modules/addonmanager.js:285:24)
at PluginManager.loadAddon (webpack-internal:///./src/modules/pluginmanager.js:117:25)
at PluginManager.loadAllAddons (webpack-internal:///./src/modules/addonmanager.js:396:26)
at PluginManager.initialize (webpack-internal:///./src/modules/addonmanager.js:107:17)
at PluginManager.initialize (webpack-internal:///./src/modules/pluginmanager.js:68:26)
at Core.startup (webpack-internal:///./src/modules/core.js:86:81)
```
This error appears in versions 1.1.0 and 1.1.1. For me, the plugin works on version 1.0.8

**Comment by Taimoor-Tariq** [comment]
I'll look into it, in the mean while, just try to copy the raw js from the file into the plugin file on your computer and try it.

link to raw JS: https://raw.githubusercontent.com/Taimoor-Tariq/BetterDiscordStuff/main/Plugins/SendTimestamps/SendTimestamps.plugin.js

**Comment by Serega007RU** [comment]
It also throws an error
Here is this working version for me: https://raw.githubusercontent.com/Taimoor-Tariq/BetterDiscordStuff/a4aa5ba22ecbd843b1e7ae0a99beee2fe8f6d59b/Plugins/SendTimestamps/SendTimestamps.plugin.js

**Comment by Serega007RU** [comment]
Perhaps this error is due to the fact that I use the browser BetterDiscord, I have 50+ plugins, everything works fine except SendTimestamps 1.1.x

Here is a link to the Better Discord browser extension https://github.com/Strencher/BdBrowser

**Comment by rrbailey89** [comment]
> I'll look into it, in the mean while, just try to copy the raw js from the file into the plugin file on your computer and try it.
> 
> link to raw JS: https://raw.githubusercontent.com/Taimoor-Tariq/BetterDiscordStuff/main/Plugins/SendTimestamps/SendTimestamps.plugin.js

this worked for me

**Comment by Serega007RU** [comment]
I found this error in the console
```
SendTimestamps.plugin.js:376 Could not load: ReferenceError: setFormatOpts is not defined
    at plugin (SendTimestamps.plugin.js:152)
    at eval (SendTimestamps.plugin.js:369)
    at eval (SendTimestamps.plugin.js:370)
    at eval (SendTimestamps.plugin.js:371)
    at eval (SendTimestamps.plugin.js:378)
    at eval (SendTimestamps.plugin.js:383)
    at frontend.js:1
    at HTMLHeadElement.e.<computed> [as append] (frontend.js:1)
    at PluginManager.getFileModification (pluginmanager.js?d173:112)
    at eval (addonmanager.js?cea9:199)
    at Object._require (frontend.js:1)
    at S (frontend.js:1)
    at PluginManager.loadAddon (addonmanager.js?cea9:209)
    at PluginManager.loadAddon (pluginmanager.js?d173:65)
    at PluginManager.loadAllAddons (addonmanager.js?cea9:328)
    at PluginManager.initialize (addonmanager.js?cea9:60)
    at PluginManager.initialize (pluginmanager.js?d173:37)
    at Core.startup (core.js?b6de:74)
```

**Comment by Serega007RU** [comment]
As always, you need to do everything yourself, this corrects this error #3
I apologize for the strange name of the commit, I don't do pull request every day, I can say I'm doing it for the first time

**Comment by Taimoor-Tariq** [comment]
Good job on finding the error yourself, I found the error when I ran it in the browser and fixed it last night, I just didn't push my commits. Anyway the plugin is now updated and should work fine.

**Comment by Serega007RU** [comment]
Well, the problem is solved
