### ISSUE TITLE
[ BUG | SendTimeStamps cant be constructed.

### ISSUE THREAD

**Issue by Masono03** [Taimoor-Tariq/BetterDiscordStuff#51]
**Issue**
Started today. As title states cant be constrcuted during load.

Canary 141316 (e700422)
BetterDiscord 1.6.2
Host 1.0.48 Windows 10 64-Bit (10.0.19044)

**Comment by dippyshere** [comment]
Adding onto this with the error:
```js
TypeError: Cannot read property 'locale' of undefined
    at new SendTimestamp (betterdiscord://plugins/SendTimestamps.plugin.js:226:59)
    at Object.initializeAddon (<anonymous>:4:41393)
    at Object.loadAddon (<anonymous>:4:8923)
    at Object.loadAddon (<anonymous>:4:40648)
    at Object.updateList (<anonymous>:4:10561)
    at Object.updatePluginList (<anonymous>:4:40345)
    at O.reload (<anonymous>:4:108250)
    at Object.Ye (https://canary.discord.com/assets/d81410ec2d330583c6e5.js:6010:658)
    at qe (https://canary.discord.com/assets/d81410ec2d330583c6e5.js:6010:812)
    at https://canary.discord.com/assets/d81410ec2d330583c6e5.js:6030:409
    at Pr (https://canary.discord.com/assets/d81410ec2d330583c6e5.js:6030:506)
    at Mr (https://canary.discord.com/assets/d81410ec2d330583c6e5.js:6030:920)
    at https://canary.discord.com/assets/d81410ec2d330583c6e5.js:6036:680
    at ke (https://canary.discord.com/assets/d81410ec2d330583c6e5.js:6118:404)
    at https://canary.discord.com/assets/d81410ec2d330583c6e5.js:6032:395
    at Vr (https://canary.discord.com/assets/d81410ec2d330583c6e5.js:6032:425)
    at rn (https://canary.discord.com/assets/d81410ec2d330583c6e5.js:6019:757)
    at nn (https://canary.discord.com/assets/d81410ec2d330583c6e5.js:6019:7)
    at t.unstable_runWithPriority (https://canary.discord.com/assets/d81410ec2d330583c6e5.js:6230:828)
    at Ki (https://canary.discord.com/assets/d81410ec2d330583c6e5.js:6041:117)
    at Ue (https://canary.discord.com/assets/d81410ec2d330583c6e5.js:6118:144)
    at en (https://canary.discord.com/assets/d81410ec2d330583c6e5.js:6018:800)
    at HTMLDivElement.r (https://canary.discord.com/assets/e813ffde6cadac615dfb.js:126:559)```

**Comment by Ash3781** [comment]
Can confirm same on Discord-PTB and Linux:
Ptb 141407 (be1e474)
BetterDiscord 1.6.2
Host 0.0.31 Linux 64-Bit (5.18.16-Hardened1-1-Hardened)

**Comment by aaronliu0130** [comment]
The update that broke this has now been pushed to stable.

**Comment by Martin-963** [comment]
Can also confirm on stable version
Stable 141471 (8b6078f)
BetterDiscord 1.6.2
Host 1.0.9006 Windows 10 64-Bit (10.0.22000)

**Comment by AndryS0** [comment]
As a tempory solution you can remove line 234:
```js
this.locale = UserSettingsStore.locale;
```
Like that:
```js
this.forceOnRight = false;
//this.locale = UserSettingsStore.locale;

this.sendFormatOptions = {
    0: 'F',
};
````
at least it helped me

**Comment by dippyshere** [comment]
Another solution that fixes some other plugins too is to modify line 376 in 0PluginLibrary.plugin.js from:
```js
get UserSettingsStore() {return _webpackmodules__WEBPACK_IMPORTED_MODULE_1__["default"].getByProps("guildPositions");},
```
to:
```js
get UserSettingsStore() {return _webpackmodules__WEBPACK_IMPORTED_MODULE_1__["default"].getByProps("getAllSettings", "theme");},
```
[from this pull request](https://github.com/rauenzi/BDPluginLibrary/pull/138)

**Comment by Fusezion** [comment]
I fixed my issue with
```js
this.locale = UserSettingsStore.locale;
```
simply by changing it to 
```js
this.locale = Api.DiscordModules.locale
```
since that's how it's more or less set up in the code

**Comment by Taimoor-Tariq** [comment]
Hey guys,
Sorry for being inactive for too long. I had a lot going on so I was not able to fix bugs. As you may know that the recent Discord update broke a lot of the plugins. I will attempt to fix my plugins once I figure out what the broken changes are 💛.

**Comment by code-fanatic** [comment]
> As a tempory solution you can remove line 234:
> 
> ```js
> this.locale = UserSettingsStore.locale;
> ```
> 
> Like that:
> 
> ```js
> this.forceOnRight = false;
> //this.locale = UserSettingsStore.locale;
> 
> this.sendFormatOptions = {
>     0: 'F',
> };
> ```
> 
> at least it helped me

is it still working?

**Comment by Taimoor-Tariq** [comment]
Check announcement in issue #58 [Issue](https://github.com/Taimoor-Tariq/BetterDiscordStuff/issues/58#issuecomment-1361206186)
