### ISSUE TITLE
[ BUG | SendTimestamps ] Plugin could not be compiled (BD v1.7.0)

### ISSUE THREAD

**Issue by CyberedCake** [Taimoor-Tariq/BetterDiscordStuff#58]
--> Pre note: I don't believe this is a copy of #51, lemme know if I'm wrong! <--

**Issue**
Whenever I try to install the [SendTimestamps](https://github.com/Taimoor-Tariq/BetterDiscordStuff/tree/main/Plugins/SendTimestamps) plugin, it fails to compile in the new Better Discord v1.7.0.

```
TypeError: Cannot read property 'SingleSelect' of undefined
    at Object.get Dropdown [as Dropdown] (betterdiscord://plugins/0PluginLibrary.plugin.js:554:110)
    at Object.value (betterdiscord://plugins/0PluginLibrary.plugin.js:2649:24)
    at Object.get (betterdiscord://plugins/0PluginLibrary.plugin.js:2633:26)
    at plugin (betterdiscord://plugins/SendTimestamps.plugin.js:89:72)
    at eval (betterdiscord://plugins/SendTimestamps.plugin.js:887:22)
    at eval (betterdiscord://plugins/SendTimestamps.plugin.js:888:13)
    at eval (betterdiscord://plugins/SendTimestamps.plugin.js:889:3)
    at Object.requireAddon (<anonymous>:4:43438)
    at Object.loadAddon (<anonymous>:4:9197)
    at Object.loadAddon (<anonymous>:4:41165)
    at Object.reloadAddon (<anonymous>:4:10047)
    at AsyncFunction.<anonymous> (<anonymous>:4:7387)
```

I have already tried using the fix in #51, but it still failed to compile correctly!
<br>
<img src="https://user-images.githubusercontent.com/61170080/193363272-d675565b-bff5-4cb4-bb49-a69b35ba88f3.png" data-canonical-src="https://user-images.githubusercontent.com/61170080/193363272-d675565b-bff5-4cb4-bb49-a69b35ba88f3.png" width="400" height="400" />

**Comment by Fusezion** [comment]
@CyberedCake if you're unaware, a discord update ended up breaking betterdiscord and all corresponding plugins
they'll need to update this plugin, however with the inactivity of development I doubt any time soon
![image](https://user-images.githubusercontent.com/81952476/193380103-0efb3896-8b57-4fa3-97cf-e725da829c95.png)

**Comment by CyberedCake** [comment]
> @CyberedCake if you're unaware, a discord update ended up breaking betterdiscord and all corresponding plugins
> they'll need to update this plugin, however with the inactivity of development I doubt any time soon
> ![image](https://user-images.githubusercontent.com/81952476/193380103-0efb3896-8b57-4fa3-97cf-e725da829c95.png)
> 

Yeah, I knew about that. Sucks too, because I really liked this plugin. I just can't bother to learn JS and the BdApi to fix this. Hopefully another plugin will replace this awesome one.

**Comment by Fusezion** [comment]
> > @CyberedCake if you're unaware, a discord update ended up breaking betterdiscord and all corresponding plugins
> > they'll need to update this plugin, however with the inactivity of development I doubt any time soon
> > ![image](https://user-images.githubusercontent.com/81952476/193380103-0efb3896-8b57-4fa3-97cf-e725da829c95.png)
> 
> Yeah, I knew about that. Sucks too, because I really liked this plugin. I just can't bother to learn JS and the BdApi to fix this. Hopefully another plugin will replace this awesome one.

There's most likely a few ~~better~~*(bad wording)* discord devs that would remake this maybe not as custom

**Comment by Sebas-Re** [comment]
:(

**Comment by Taimoor-Tariq** [comment]
Hey guys,
Sorry for being inactive for too long. I had a lot going on so I was not able to fix bugs. As you may know that the recent Discord update broke a lot of the plugins. I will attempt to fix my plugins once I figure out what the broken changes are 💛.

**Comment by ArcturusLight1** [comment]
Just installed better discord, this is the first plugin i went for. Best wishes to the dev, i can provide only moral support. This is the cutest "you tried running me directly" code that i've ever seen.

**Comment by CyberedCake** [comment]
> Hey guys, Sorry for being inactive for too long. I had a lot going on so I was not able to fix bugs. As you may know that the recent Discord update broke a lot of the plugins. I will attempt to fix my plugins once I figure out what the broken changes are 💛.

Hey! It's all right. I understand the absence part. Also, I feel like you should know that you can take your time, we can wait if absolutely necessary. SendTimestamps was just a nice QoL thing and, while I would love it to be back, you take all the time you need!

**Comment by ElProfessorFR** [comment]
A lot of plugin work now...

**Comment by Canada-LaVearn** [comment]
This issue still persists, hoping for a fix soon!

**Comment by Taimoor-Tariq** [comment]
Hey guys,

Huge announcement. I will be discontinuing this plugin in compliance with Discord. Discord is adding the plugins functionality to their main client.

Thank you to everyone who used my plugin ❤️.

**Comment by Taimoor-Tariq** [comment]
Screenshots of what Discord is adding

![208880731-3310633d-f806-4bea-bd5f-f061b86c4816](https://user-images.githubusercontent.com/45585081/208896552-48e447f1-3db1-4af5-ad3d-28660ffb3eff.png)
![208880618-db42dc3c-fb27-447e-8f5f-9804f5a4728c](https://user-images.githubusercontent.com/45585081/208896554-fa7166c1-4f6e-4632-8f01-4d67eeb041ad.png)

**Comment by Taimoor-Tariq** [comment]
Screenshots of what Discord is adding

![208880731-3310633d-f806-4bea-bd5f-f061b86c4816](https://user-images.githubusercontent.com/45585081/208896552-48e447f1-3db1-4af5-ad3d-28660ffb3eff.png)
![208880618-db42dc3c-fb27-447e-8f5f-9804f5a4728c](https://user-images.githubusercontent.com/45585081/208896554-fa7166c1-4f6e-4632-8f01-4d67eeb041ad.png)

**Comment by aaronliu0130** [comment]
How is this feature triggered? Is it only in canary/ptb?

**Comment by rexkix** [comment]
> Hey guys,
> 
> Huge announcement. I will be discontinuing this plugin in compliance with Discord. Discord is adding the plugins functionality to their main client.
> 
> Thank you to everyone who used my plugin ❤️.

EDIT: I see now that Discord is adding something that fills the bill.  Never mind.

~~Hello Taimoor.  If I can find somebody who can take over the plugin, would that be acceptable to you somehow.  How should they reach out to you?  I do have somebody in mind.  I'm good friends with samfundev who fixed the ChannelTabs plugin.

Please advise.  Thanks for an amazing plugin and good luck to you.~~

**Comment by CyberedCake** [comment]
> Screenshots of what Discord is adding
> 
> ![208880731-3310633d-f806-4bea-bd5f-f061b86c4816](https://user-images.githubusercontent.com/45585081/208896552-48e447f1-3db1-4af5-ad3d-28660ffb3eff.png) ![208880618-db42dc3c-fb27-447e-8f5f-9804f5a4728c](https://user-images.githubusercontent.com/45585081/208896554-fa7166c1-4f6e-4632-8f01-4d67eeb041ad.png)

Looks pretty awesome! Thank you for the work you did on the plugin before Discord adds their own! Really appreciate developers like you who dedicate time to stuff like this, even if it ends up getting added to the client (which should be considered a win!).

**Comment by Masono03** [comment]
> Screenshots of what Discord is adding
> 
> ![208880731-3310633d-f806-4bea-bd5f-f061b86c4816](https://user-images.githubusercontent.com/45585081/208896552-48e447f1-3db1-4af5-ad3d-28660ffb3eff.png) ![208880618-db42dc3c-fb27-447e-8f5f-9804f5a4728c](https://user-images.githubusercontent.com/45585081/208896554-fa7166c1-4f6e-4632-8f01-4d67eeb041ad.png)

oh? how do u acticate that :0 cant find the entry for it in experiments

**Comment by louis1706** [comment]
i would like to know how use this ?

**Comment by vivvyinks** [comment]
I also wanna know... how do you get this feature?

**Comment by Sebas-Re** [comment]
F?

**Comment by Tyrand** [comment]
The Discord implantation is still not released.

**Comment by aurkaxi** [comment]
F

**Comment by ArcturusLight1** [comment]
What does "in compliance with Discord" mean?

**Comment by aaronliu0130** [comment]
@Taimoor-Tariq when will this discord feature come?

**Comment by Soulivan71** [comment]
The discord, feature never going to be release .. its in dev since 12/2022

**Comment by Taimoor-Tariq** [comment]
I have decided to work on the plugin again since I am starting to get more free time.
Expect updates within the next few weeks.

Thank you all for all your patience ❤️

**Comment by Soulivan71** [comment]
Okay thx !

**Comment by AnonymousX86** [comment]
Error still exists:
```js
TypeError: Cannot read properties of undefined (reading 'ComponentDispatch')
    at plugin (betterdiscord://plugins/SendTimestamps.plugin.js:91:91)
    at eval (betterdiscord://plugins/SendTimestamps.plugin.js:887:22)
    at eval (betterdiscord://plugins/SendTimestamps.plugin.js:888:13)
    at eval (betterdiscord://plugins/SendTimestamps.plugin.js:889:3)
    at M.requireAddon (betterdiscord/renderer.js:4:35818)
    at M.loadAddon (betterdiscord/renderer.js:4:8323)
    at M.loadAddon (betterdiscord/renderer.js:4:33490)
    at M.loadAllAddons (betterdiscord/renderer.js:4:10795)
    at M.initialize (betterdiscord/renderer.js:4:5219)
    at M.initialize (betterdiscord/renderer.js:4:32689)
    at Object.startup (betterdiscord/renderer.js:4:359757)
```
Friendly reminder.
I have an idea. Maybe Instead of sending timestamp as plain text, send built-in timestamps? Currently I'm using this: <https://r.3v.fi/discord-timestamps/>, but it would be great to be able to do this within client and don't switch to the website.

**Comment by aaronliu0130** [comment]
The plug-in is supposed to send built-in time stamps, I don’t know why you think it sends as plain text. HammerTime is a better web GUI for these.

**Comment by Sebas-Re** [comment]
Just use Vencord, people, it has most BD plugins and works better in terms of performance

**Comment by aaronliu0130** [comment]
Excuse me, Replugged is way better. Bundling plug-ins is bloat and having most BD plugins is a weakness because of DevilBro. Replugged also has no dependency hell and has mature theme and plug-in packaging. No memory issues either.

**Comment by Sebas-Re** [comment]
Or Reppluged, yeah! Whichever works best, just trying to enfasize there's always alternatives for this issue, especially if you only use the timestamp plugin (Although I think replugged didn't have that one? Don't remember)

**Comment by aaronliu0130** [comment]
Hmm, I’m surprised that it doesn’t.

**Comment by QuentinMcCarthy** [comment]
> Hey guys,
> 
> Huge announcement. I will be discontinuing this plugin in compliance with Discord. Discord is adding the plugins functionality to their main client.
> 
> Thank you to everyone who used my plugin ❤️.

wdym by in compliance? BD is in itself non-compliant with Discord. I see no reason not to continue with this plugin until it becomes redundant, because as it is there **is no way to send timestamps in Discord**. This plugin is the only way and it's inoperable, plus we don't know WHEN Discord will add their own feature for it.

**Comment by aaronliu0130** [comment]
@QuentinMcCarthy Firstly, see their reply on August 18. Secondly, it’s not like violating Discord, it’s that at the time they thought this plugin was going to be redundant soon.

**Comment by jacobmix** [comment]
Since Discord is clearly not adding this any time soon, it'd be nice to at least have a plugin that does the job.
Not sure Discord ever officially mention a release date. All i find is a reddit post:
https://old.reddit.com/r/discordapp/comments/zrgfku/discord_is_adding_a_ui_for_editing_timestamps/
Hope the plugin returns.

**Comment by QuentinMcCarthy** [comment]
@aaronliu0130 My bad I didn't see their response saying they were working on it again.

**Comment by QuentinMcCarthy** [comment]
Temporary fix here: https://github.com/Taimoor-Tariq/BetterDiscordStuff/issues/63#issuecomment-1926223637
