### ISSUE TITLE
[ BUG | VoiceUtilities ] - Not loading

### ISSUE THREAD

**Issue by Soulivan71** [Taimoor-Tariq/BetterDiscordStuff#60]
**Issue**
TypeError: Cannot read property 'ChannelTypes' of undefined
    at plugin (betterdiscord://plugins/VoiceUtilities.plugin.js:63:51)
    at eval (betterdiscord://plugins/VoiceUtilities.plugin.js:295:22)
    at eval (betterdiscord://plugins/VoiceUtilities.plugin.js:296:13)
    at eval (betterdiscord://plugins/VoiceUtilities.plugin.js:297:3)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at Object.loadAllAddons (<anonymous>:4:11637)
    at Object.initialize (<anonymous>:4:6059)
    at Object.initialize (<anonymous>:4:36059)
    at Object.startup (<anonymous>:4:396505)

**Comment by BobTheLouis** [comment]
same
