### ISSUE TITLE
An error was encountered while trying to load this plugin.

### ISSUE THREAD

**Issue by Pyddkae** [Taimoor-Tariq/BetterDiscordStuff#62]
how do i fix this?

**Comment by LukysGaming** [comment]
+1

**Comment by RisingEclipse** [comment]
Issue persists on latest Better Discord

**Comment by Teksura** [comment]
Experiencing the same. It spits out the following error:

```
TypeError: Cannot read property 'SingleSelect' of undefined
    at Object.get Dropdown [as Dropdown] (betterdiscord://plugins/0PluginLibrary.plugin.js:581:110)
    at Object.value (betterdiscord://plugins/0PluginLibrary.plugin.js:2515:24)
    at Object.get (betterdiscord://plugins/0PluginLibrary.plugin.js:2499:26)
    at plugin (betterdiscord://plugins/SendTimestamps.plugin.js:89:72)
    at eval (betterdiscord://plugins/SendTimestamps.plugin.js:869:22)
    at eval (betterdiscord://plugins/SendTimestamps.plugin.js:870:13)
    at eval (betterdiscord://plugins/SendTimestamps.plugin.js:871:3)
    at Object.requireAddon (betterdiscord/renderer.js:4:35265)
    at Object.loadAddon (betterdiscord/renderer.js:4:7766)
    at Object.loadAddon (betterdiscord/renderer.js:4:32937)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:4:5758)```

**Comment by Soft-Water** [comment]
Discord broke some plugins a couple updates ago.  This one never got fixed.

**Comment by QuentinMcCarthy** [comment]
Temporary fix here: https://github.com/Taimoor-Tariq/BetterDiscordStuff/issues/63#issuecomment-1926223637
