### ISSUE TITLE
[ BUG | SendTimestamps ] - Plugin fails to load

### ISSUE THREAD

**Issue by VenoPhage** [Taimoor-Tariq/BetterDiscordStuff#63]
**Issue**
after installing bd cant load the plugin giving this error msg.
`An error was encountered while trying to load this plugin.`

![image](https://user-images.githubusercontent.com/73802442/231632791-e3e356af-87b9-4788-b600-3cdaf670578f.png)

**Comment by Normolo** [comment]
Managed to get this error log
```js
TypeError: Cannot read properties of undefined (reading 'ComponentDispatch')
    at plugin (betterdiscord://plugins/SendTimestamps.plugin.js:91:91)
    at eval (betterdiscord://plugins/SendTimestamps.plugin.js:869:22)
    at eval (betterdiscord://plugins/SendTimestamps.plugin.js:870:13)
    at eval (betterdiscord://plugins/SendTimestamps.plugin.js:871:3)
    at A.requireAddon (betterdiscord/renderer.js:4:35124)
    at A.loadAddon (betterdiscord/renderer.js:4:7625)
    at A.loadAddon (betterdiscord/renderer.js:4:32796)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:4:5617)
   ```

**Comment by NapoII** [comment]
Same. Please update the plugin I really need it.

**Comment by Dr-Isaac-Kleiner** [comment]
has he really not fixed it in over 2 months? i get the same error

**Comment by developomp** [comment]
The plugin has been discontinued and will be implemented on discord's client.
https://github.com/Taimoor-Tariq/BetterDiscordStuff/issues/58#issuecomment-1361206186

**Comment by NapoII** [comment]
sad and happy but sad

**Comment by QuentinMcCarthy** [comment]
For anyone still waiting for an update, for now refer to the changes here:
https://github.com/Taimoor-Tariq/BetterDiscordStuff/pull/53/commits/cf63114fb971fdc04fffda8e883a097c144e6c59

Manually make the above changes in the plugin, and it'll work. You're gonna have to add some extra stuff though to get the option to appear. In the settings for the plugin, set it to "In Attach Menu", the other option will not work. Then, go to your custom CSS and enter:
`.optionLabel-1o-h-l {
    color:white;
}`

The option should then appear in the attachment menu. If it doesn't, simply use the developer tools with the attachment menu open (ctrl + shift + i with developer options enabled), go to the element picker in the top left of the console, then click the top part of the attachment menu. You should see a div with an svg in it, you want the div's class, copy and past it to replace the optionLabel in the code above.

I apologise if those instructions aren't clear, but the plugin will still function without the custom CSS, but the option will be coloured black and impossible to see in the attachment menu (it's still there though, and still clickable)

Boom, it's now working. If you'd like, look at the other pull request here: https://github.com/Taimoor-Tariq/BetterDiscordStuff/pull/50/commits/51bedf59be990b055f2fd1abac51ab8cea8336b8 and make that change too

**Comment by NapoII** [comment]
![zoYXGd7](https://github.com/Taimoor-Tariq/BetterDiscordStuff/assets/88168538/0bdc0a10-1cd3-4062-b4dd-22ac95079273)

**Comment by QuentinMcCarthy** [comment]
Is that using the fix in the pull request? Because it only works via the method I said in my comment, for me

**Comment by CuantumQ** [comment]
You can use these two lines of CSS to make the look like the Attach Menu option actually belongs in discord's default dark mode style instead of just. awkwardly existing on top of the menu.
```
.optionLabel-1o-h-l { color:rgb(181,186,193); padding:8px 10px 8px 10px; border-radius:2px;}
.optionLabel-1o-h-l:hover { color:white; background-color:rgb(71,82,196);}
```
Though, it does have an issue where the actual Upload a File option doesn't stop being highlighted (mostly because the option gets highlighted by hovering over the option, but doesn't unhighlight unless you bring your mouse out of the menu all together. So I'm not quite sure how you would make it not stay highlighted.) At least it makes it mostly look nicer

**Comment by QuentinMcCarthy** [comment]
Thanks, my goal was simply to find a fix and share it, I couldn't be bothered to dig into the CSS to get it fully "fitting"
